### ISSUE TITLE
ggside throws an error 

### ISSUE THREAD

**Issue by RedTent** [jtlandis/ggside#11] opened 2021-05-24 08:34 UTC
When I have  a plot  in which the x-axis is of class Date, adding a sidepanel on the y-axis throws an error (_Error: Invalid input: date_trans works with objects of class Date only_). I think this is because the class of the x-axis of the main panel and the class of the x-axis of the side panel are different, The solution to this would be to make the axis of the sidepanel somehow independent of the main panel.

I've made a reprex to illutrate the problem:

``` r
library(magrittr)
library(ggplot2)

# Works like I expect
tibble::tibble(numbers = 1:10, values = rnorm(10)) %>% 
  ggplot(aes(numbers, values)) +
  geom_line() +
  ggside::geom_ysidehistogram(binwidth = 0.5)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
```

![](https://i.imgur.com/E8XhgQc.png)

``` r

# Works like I expect
tibble::tibble(dates = Sys.Date() - 10:1, values = rnorm(10)) %>% 
  ggplot(aes(dates, values)) +
  geom_line()
```

![](https://i.imgur.com/qSOMRCE.png)

``` r

# Throws error
tibble::tibble(dates = Sys.Date() - 10:1, values = rnorm(10)) %>% 
  ggplot(aes(dates, values)) +
  geom_line() +
  ggside::geom_ysidehistogram(binwidth = 0.5)
#> Error: Invalid input: date_trans works with objects of class Date only

# Throws error
tibble::tibble(dates = Sys.Date() - 10:1, values = rnorm(10)) %>% 
  ggplot(aes(dates, values)) +
  geom_line() +
  ggside::geom_ysidefreqpoly()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Error: Invalid input: date_trans works with objects of class Date only
```

![](https://i.imgur.com/0QwMRfM.png)

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RedTent** [comment] 2021-05-24 08:37
Probably there should be a function `ggside::scale_xsidey_date()`

**Comment by jtlandis** [comment] 2021-05-24 16:06
I've done some digging into the code, and I can confirm that this is not *technically* an issue with `ggside`. With the latest release of `ggside`, I do allow for scale overrides, but I've only really considered the cases of continuous ranges and discrete ranges. However, `ggplot2` makes the assumption that all panels will be from the same `Scale` ggproto class. 

The issue is that the x-axis is coerced into a `ScaleContinuousDate` object, and once it sees data that isn't of class `Date` (in other words, when it encounters a calculated variable like `after_stat(count)`), it throws an error. You can reproduce this error in base `ggplot2`.

``` r
library(magrittr)
library(ggplot2)
tibble::tibble(dates = Sys.Date() - 10:1, values = rnorm(10)) %>% 
  ggplot(aes(values)) +
  geom_line(aes(x = dates)) +
  geom_histogram(orientation = "y",binwidth = 0.5)
#> Error: Invalid input: date_trans works with objects of class Date only
```

![](https://i.imgur.com/r0RhhDE.png)

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Since this is technically an issue with `ggplot2`, I'm not sure if this is something I could fix. The issue is technically in the `map_statistic` method of the `Layer` class.  Specifically the following chunk:

```r
    # Transform the values, if the scale say it's ok
    # (see stat_spoke for one exception)
    if (self$stat$retransform) {
      stat_data <- scales_transform_df(plot$scales, stat_data)
    }
```
In this chunk, whatever the `stat_data` is (usually a continuous variable) is then checked against all of the scales. Since the main panel's x-scale is `ScaleContinuousDate`, it throws an error.

I would like to keep what `ggside` overwrites from `ggplot2` to a minimum.

Ideally, `scales_transform_df` would only use the scales from the panels that `stat_data` originates. I already make my own `XLayer` and `YLayer` ggproto class that I could potentially make this tweak, but this wont fix the base behavior of `ggplot2`, and even then the rewrite may introduce more bugs.

Thanks for bringing this to my attention!

**Comment by jtlandis** [comment] 2021-05-24 16:57
Upon a little more digging, I'm finding my initial assumptions to be incorrect. The issue is still in that previous chunk, but making sure they only use the correct panel is a bit more complicated than anticipated. 

In short `plot$scales` is an untrained version of what exists on `layout$panel_scales_(x|y)`. At least for this simple case, the only two scales that exist on `plot$scales$scales` are what I assume are prototypes of the x and y axis, which makes sense, since all its trying to do is find how to transform the data correctly.

`layout$panel_scales_(x|y)` contain the information regarding the correct scale for a particular panel, but this information is not readily available within the `map_statistic` scope. Thus, if I were to do a rewrite, I would first have to grab the `layout` object from the `ggplot_build.ggplot` scope. A bit inelegant, but still doable.

**Comment by jtlandis** [comment] 2021-05-27 15:40
I made some progress on this issue, modifying the `XLayer` and `YLayer` objects. I am hoping that this will be quite self contained, but if you find any other issues, please let me know.

``` r
library(dplyr)
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

set.seed(1234)
# fake data
df <- data.frame(year = sample(2000:2020, 300, replace = T),
                 month = sample(1:12, 300, replace = T),
                 day = sample(1:28,300, replace = T),
                 temperature = rnorm(300, 70, 8)) %>%
  mutate(
    month_name = month.name[month],
    date = as.Date(sprintf("%04d-%02d-%02d",year, month, day))
  )

#base ggplot
p <- ggplot(df, aes(x = date, y = temperature)) +
  geom_line() +
  geom_point(aes(color = month_name))
```

On this new version, the base behavior of `ggplot2` is retained, in which mapping a calculated statistic to a previously defined `Date` scale will result in an error.

```r
p + geom_ysidehistogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Error: Invalid input: date_trans works with objects of class Date only
```

To avoid this, you will need to specify the axis for that side panel manually

```r
p + geom_ysidehistogram() + scale_ysidex_continuous()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/uHCcAZM.png)

Of course, putting a `xsidehistogram` on an axis of `ScaleContinuousDate` doesn't require any additional specification, since they share an axis and the `y` aesthetic is the calculated statistic in this case.

``` r
p + geom_xsidehistogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/9TBzbMG.png)

<sup>Created on 2021-05-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This is currently on the `dev` branch of this repository. It will be a while before I release a new version as CRAN generally wont accept resubmissions within 3 months of each other unless there is a critical bug.

**Closed by jtlandis** 2021-05-27 15:40 UTC
Labels: bug, ggplot2 issue

**Comment by jtlandis** [comment] 2021-08-16 20:00
I am considering removing this feature in order for `ggside` to remain as stable as possible to the ongoing development of `ggplot2`. Reimplementing internal `ggproto` classes is a hacky solution and will break down as soon as `ggside` and `ggplot2`'s implementation are out of sync.
